MVC 3/Notesmarketplace1/Controllers/AdminActivityController.cs
using Notesmarketplace1.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;

namespace Notesmarketplace1.Controllers
{
    public class AdminActivityController : Controller
    {
        private readonly notemarketplaceEntities dbobj = new notemarketplaceEntities();
        // GET: AdminActivity
        [Authorize(Roles = "SuperAdmin,Admin")]
        public ActionResult NotesUnderReview(string searchtext, string currentFilter, int? page, string sortorder, string Seller)
        {

            ViewBag.CurrentSort = sortorder;
            ViewBag.AddedDateparam = string.IsNullOrEmpty(sortorder) ? "Date Desc" : "";
            ViewBag.Titleparam = sortorder == "Title" ? "Title_desc" : "Title";
            ViewBag.Categoryparam = sortorder == "Category" ? "Category_desc" : "Category";
            ViewBag.Seller1 = sortorder == "Seller" ? "Seller_desc" : "Seller";
            ViewBag.Statuspeparam = sortorder == "Status" ? "Status_desc" : "Status";

            List<SellerNote> sellerNotes = dbobj.SellerNotes.Where(x => x.IsActive == true).ToList();
            List<NoteCategory> noteCategories = dbobj.NoteCategories.ToList();
            List<Referencedata> referencedatas = dbobj.Referencedatas.Where(x => x.RefCategory == "note status" && x.value == "submitted for review" || x.value == "in review").ToList();
            List<User> userdatas = dbobj.Users.ToList();
            if (searchtext != null)
            {
                page = 1;
            }
            else
            {
                searchtext = currentFilter;
            }
            ViewBag.CurrentFilter = searchtext;
            var tabledetails = from s in sellerNotes
                               join n in noteCategories on s.Category equals n.Id into table1
                               from n in table1.ToList()
                               join r in referencedatas on s.Status equals r.Id into table2
                               from r in table2.ToList()
                               join u in userdatas on s.SellerID equals u.ID into table3
                               from u in table3.ToList()
                               where (r.value == "submitted for review" || r.value == "in review" && ((u.ID.ToString() == Seller || String.IsNullOrEmpty(Seller))))
                               select new DashboardClass
                               { sellernotedetail = s, notecategorydetail = n, referencedatadetail = r, userdetail = u };
            if (!String.IsNullOrEmpty(searchtext))
            {
                tabledetails = tabledetails.Where(x => x.notecategorydetail.name.Contains(searchtext) ||
                 x.sellernotedetail.Title.Contains(searchtext) || x.referencedatadetail.value.Contains(searchtext) ||
                 x.sellernotedetail.CreatedDate.ToString().Contains(searchtext) ||
                 x.userdetail.FirstName.Contains(searchtext) || searchtext == null);
            }
            switch (sortorder)
            {
                case "Date Desc":
                    tabledetails = tabledetails.OrderByDescending(x => x.sellernotedetail.CreatedDate);
                    break;
                case "Title":
                    tabledetails = tabledetails.OrderByDescending(x => x.sellernotedetail.Title);
                    break;
                case "Title_desc":
                    tabledetails = tabledetails.OrderBy(x => x.sellernotedetail.Title);
                    break;
                case "Category":
                    tabledetails = tabledetails.OrderByDescending(x => x.notecategorydetail.name);
                    break;
                case "Category_desc":
                    tabledetails = tabledetails.OrderBy(x => x.notecategorydetail.name);
                    break;
                case "Status":
                    tabledetails = tabledetails.OrderByDescending(x => x.referencedatadetail.value);
                    break;
                case "Status_desc":
                    tabledetails = tabledetails.OrderBy(x => x.referencedatadetail.value);
                    break;
                case "Seller":
                    tabledetails = tabledetails.OrderByDescending(x => x.sellernotedetail.User1.FirstName);
                    break;
                case "Seller_desc":
                    tabledetails = tabledetails.OrderBy(x => x.sellernotedetail.User1.FirstName);
                    break;
                default:
                    tabledetails = tabledetails.OrderBy(x => x.sellernotedetail.CreatedDate);
                    break;
            }
            ViewBag.Seller2 = dbobj.Users.Where(x => x.IsEmailVerified == true && x.RoleID == dbobj.UserRoles.Where(a => a.Name.ToLower() == "member").Select(a => a.ID).FirstOrDefault());
            return View(tabledetails.ToPagedList(page ?? 1, 5));


        }

        public ActionResult InReview(int id)
        {
            SellerNote sellrnote = dbobj.SellerNotes.Find(id);
            if (sellrnote != null && sellrnote.Referencedata.value == "submitted for review")
            {
                sellrnote.Status = dbobj.Referencedatas.Where(x => x.RefCategory.ToLower() == "note status" && x.value.ToLower() == "in review").Select(x => x.Id).FirstOrDefault();
            }
            dbobj.Entry(sellrnote).State = EntityState.Modified;
            dbobj.SaveChanges();
            return RedirectToAction("AdminDashboard", "Admin");
        }
        public ActionResult Approve(int id)
        {
            var Emailid = User.Identity.Name.ToString();
            User user = dbobj.Users.Where(x => x.EmailId == Emailid).FirstOrDefault();
            SellerNote sellrnote = dbobj.SellerNotes.Find(id);
            if (sellrnote != null && (sellrnote.Referencedata.value == "submitted for review" || sellrnote.Referencedata.value == "in review" || sellrnote.Referencedata.value == "rejected"))
            {
                sellrnote.Status = dbobj.Referencedatas.Where(x => x.RefCategory.ToLower() == "note status" && x.value.ToLower() == "published").Select(x => x.Id).FirstOrDefault();
                sellrnote.ActionedBy = user.ID;
                sellrnote.Publisheddate = DateTime.Now;
            }
            dbobj.Entry(sellrnote).State = EntityState.Modified;
            dbobj.SaveChanges();
            return RedirectToAction("AdminDashboard", "Admin");

        }
        [HttpPost]
        public ActionResult RejectNote(int id, string remarks)
        {
            var Emailid = User.Identity.Name.ToString();
            User user = dbobj.Users.Where(x => x.EmailId == Emailid).FirstOrDefault();
            SellerNote sellrnote = dbobj.SellerNotes.Find(id);

            if (sellrnote != null && (sellrnote.Referencedata.value == "submitted for review" || sellrnote.Referencedata.value == "in review"))
            {

                sellrnote.Status = dbobj.Referencedatas.Where(x => x.RefCategory.ToLower() == "note status" && x.value.ToLower() == "rejected").Select(x => x.Id).FirstOrDefault();
                sellrnote.ActionedBy = user.ID;
                sellrnote.ModifiedDate = DateTime.Now;
                sellrnote.AdminRemarks = remarks;

            }
            dbobj.Entry(sellrnote).State = EntityState.Modified;
            dbobj.SaveChanges();
            return RedirectToAction("AdminDashboard", "Admin");

        }


        [HttpPost]
        public ActionResult Unpublish(int id, string remarks)
        {
            var Emailid = User.Identity.Name.ToString();
            User user = dbobj.Users.Where(x => x.EmailId == Emailid).FirstOrDefault();
            SellerNote sellrnote = dbobj.SellerNotes.Find(id);
            SystemConfiguration system = dbobj.SystemConfigurations.Where(x => x.Key == "SupportEmail").FirstOrDefault();
            SystemConfiguration system1 = dbobj.SystemConfigurations.Where(x => x.Key == "Password").FirstOrDefault();

            if (sellrnote != null && (sellrnote.Referencedata.value == "published"))
            {
                User objuser = dbobj.Users.Where(x => x.ID == sellrnote.SellerID).FirstOrDefault();
                sellrnote.Status = dbobj.Referencedatas.Where(x => x.RefCategory.ToLower() == "note status" && x.value.ToLower() == "removed").Select(x => x.Id).FirstOrDefault();
                sellrnote.ActionedBy = user.ID;
                sellrnote.ModifiedDate = DateTime.Now;
                sellrnote.AdminRemarks = remarks;
                SendEmailtoSellerforUnPublish(objuser.EmailId.ToString(), id, system.Value, system1.Value);
            }
            dbobj.Entry(sellrnote).State = EntityState.Modified;
            dbobj.SaveChanges();
            return RedirectToAction("AdminDashboard", "Admin");

        }
        [NonAction]
        public void SendEmailtoSellerforUnPublish(string emailID, int id, string support, string password)
        {

            User objuser = dbobj.Users.Where(x => x.EmailId == emailID).FirstOrDefault();
            SellerNote objseller = dbobj.SellerNotes.Where(x => x.SellerID == objuser.ID && x.Id == id).FirstOrDefault();
            var fromEmail = new MailAddress(support, "Notemarketplace");
            var toEmail = new MailAddress(emailID);
            var fromEmailPassword = password; // Replace with actual password
            string subject = "Sorry! We need to remove your notes from our portal.";
            string body = "Hello " + " " + objuser.FirstName + "<br/>";
            body += "<br/>We want like to inform you that, your note" + " " + objseller.Title + " " + " has been removed from the portal.<br/>" +
                "Please find our remarks as below-<br/>"
                + objseller.AdminRemarks;
            ;
            body += "<br/><br/>Regards,<br/>";
            body += "Notes marketplace";
            var smtp = new SmtpClient
            {
                Host = "smtp.gmail.com",

MVC 3/Notesmarketplace1/Views/Admin/AdminDashboard.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<Notesmarketplace1.Models.DashboardClass>
@{
    ViewBag.Title = "AdminDashboard";
}
@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="dashboard-title-wrapper">
    <div class="container-ds01">


        <h1>Dashboard</h1>
        <div class="row">
            <div class="col-md-4 ">
                <div class="earning-detail text-center">
                    <a href="/AdminActivity/NotesUnderReview">
                        <h4>@ViewBag.InReview</h4>
                    </a>
                    <p>Numbers of Notes in Review for Publish</p>
                </div>
            </div>
            <div class="col-md-4 ">
                <div class="number-detail text-center">
                    <a href="/AdminActivity/AdminDownlodNotes">
                        <h4>@ViewBag.DownloadNotes</h4>
                    </a>
                    <p>Numbers of New Notes Downloaded <br>(Last 7 days)</p>
                </div>
            </div>
            <div class="col-md-4 ">
                <div class="num-detail text-center">
                    <a href="/MemberDetail/Member">
                        <h4>@ViewBag.Registration</h4>
                    </a>
                    <p>Numbers of New Regitration(Last 7 days)</p>
                </div>
            </div>
        </div>


    </div>
</div>
<div class="extra">
    <div class="title-section">
        @using (Html.BeginForm("AdminDashboard", "Admin", FormMethod.Get, new { @id = "submitform" }))
        {
            <div class="row">
                <div class="col-md-6">
                    <h2>Published Notes </h2>
                </div>

                <div class="col-md-3">
                    <div class="btn-search">
                        <input type="text" name="searchtext" id="place-search" placeholder="   &#xF002;    Search">
                    </div>
                </div>
                <div class="col-md-1">
                    <button type="submit" id="button-search">SEARCH</button>
                </div>

                <div class="col-md-2">

                    @Html.DropDownList("Month", new SelectList(ViewBag.Month, "Value", "Text"), "Select month", new { @class = "form-control month-dd", @id = "month", name = "Month", onchange = "SubmitForm()" })

                </div>
            </div>
        }
    </div>

    <div class="table-responsive">
        <table class="table border">
            <thead>
                <tr style="height: 75px; font-weight: 600;">

                    <th style="vertical-align: middle;text-align:center;" scope="col">SR NO.</th>
                    <th style="vertical-align: middle;text-align:center;" scope="col">
                        @Html.ActionLink("TITLE", "AdminDashboard", new { sortorder = ViewBag.Titleparam })
                    </th>
                    <th style="vertical-align: middle;text-align:center;" scope="col">
                        @Html.ActionLink("CATEGORY", "AdminDashboard", new { sortorder = ViewBag.Categoryparam })
                    </th>
                   
                    <th style="vertical-align: middle;text-align:center;" scope="col">
                        @Html.ActionLink("SELL TYPE", "AdminDashboard", new { sortorder = ViewBag.Selltypeparam })
                    </th>
                    <th style="vertical-align: middle;text-align:center;" scope="col">
                        @Html.ActionLink("PRICE", "AdminDashboard", new { sortorder = ViewBag.Pricepeparam })
                    </th>
                    <th style="vertical-align: middle;text-align:center;" scope="col">
                        @Html.ActionLink("PUBLISHER", "AdminDashboard", new { sortorder = ViewBag.Publisher })
                    </th>
                    <th style="vertical-align: middle;text-align:center;" scope="col">
                        @Html.ActionLink("PUBLISHED DATE", "AdminDashboard", new { sortorder = ViewBag.AddedDateparam })
                    </th>
                    <th style="vertical-align: middle;text-align:center;" scope="col">
                        @Html.ActionLink("NUMBER OF DOWNLOADS", "AdminDashboard", new { sortorder = ViewBag.Download })
                    </th>
                    <th style="vertical-align: middle;text-align:center;" scope="col"> </th>

                </tr>
            </thead>
            <tbody>
                @if (Model.Count() == 0)
                {
                    <tr>
                        <td colspan="6" class="text-center">
                            No any record found
                        </td>
                    </tr>
                }
                @{
                    var count = 0;
                }
                @foreach (var item in Model)
                {
                    <tr class="table1">
                        <td style="vertical-align: middle;text-align:center;" class="table-center"> @(count + ((Model.PageNumber - 1) * Model.PageSize) + 1)</td>
                        <td style="color:#6255a5; vertical-align: middle;text-align:center;"><a href="/Admin/AdminNotesDetail/@item.sellernotedetail.Id" style="color:#6255a5;">@item.sellernotedetail.Title</a></td>
                        <td style="vertical-align: middle;text-align:center;">@item.notecategorydetail.name</td>
                       
                        <td style="vertical-align: middle;text-align:center;">
                            @if (@item.sellernotedetail.IsPaid == true)
                            {<p>Paid</p>}
                            else
                            {
                                <p>Free</p>
                            }
                        </td>
                        <td style="vertical-align: middle;text-align:center;">&#36;@item.sellernotedetail.SellingPrice</td>
                        <td style="vertical-align: middle;text-align:center;">@item.sellernotedetail.User1.FirstName @item.sellernotedetail.User1.LastName</td>
                        <td style="vertical-align: middle;text-align:center;">@item.sellernotedetail.Publisheddate</td>
                        <td style="color: #6255a5;vertical-align: middle;text-align:center;"><a href="/AdminActivity/AdminDownlodNotes" style="color:#6255a5;">@item.sellernotedetail.Downloads.Where(x => x.isSellerhasAllowedDownloaded == true).Select(x => x.NoteId).Count()</a></td>
                        <td style="vertical-align: middle;text-align:center;">

                            <div class="dropdown2">
                                <img src="~/Content/img/front-images/dots.png" class="dots">
                                <div class="dropdown-content2">
                                    <a href="/UserActivity/Download/@item.sellernotedetail.Id">Download Notes</a>
                                    <a href="/Admin/AdminNotesDetail/@item.sellernotedetail.Id">View More Details</a>
                                    <a href="#" data-toggle="modal" data-target="#exampleModal_@item.sellernotedetail.Id">Unpublish</a>
                                </div>
                            </div>
                            <!-- Unpublish popup -->
                            <div class="modal fade " id="exampleModal_@item.sellernotedetail.Id" tabindex="-1" role="dialog" aria-labelledby="exampleModalScrollableTitle" aria-hidden="true">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content text-left Rejectpopup">
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close" value="Cancel">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                        @using (Html.BeginForm("Unpublish", "AdminActivity", FormMethod.Post))
                                        {
                                            <div class="modal-body">
                                                <input type="hidden" name="id" value="@item.sellernotedetail.Id" />
                                                <h4>@item.sellernotedetail.Title</h4>

                                                <label for="text-area"><span class="review-label">Remarks*</span></label>
                                                <textarea class="form-control user" placeholder="Write Remarks" rows="7" name="remarks" required></textarea>
                                                <br>
                                                <form style="float:right; margin-bottom:20px;">
                                                    <button type="submit" class="button-green" onclick="return confirm('Are you sure you want to Unpublish this note? ?');">Unpublish</button><button type="button" class="cancel-button button-blue" data-dismiss="modal" aria-label="Close" value="Cancel">Cancel</button>

                                                </form>
                                            </div>
                                        }
                                    </div>

                                </div>
                            </div>
                        </td>

                    </tr>
                    count++;
                }

            </tbody>
        </table>
    </div>
</div>
<div class="text-center">
    <ul class="pagination">
        <li>
            Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

            @Html.PagedListPager(Model, page => Url.Action("AdminDashboard",
                new { page, sortorder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter })
       , new PagedListRenderOptions() { MaximumPageNumbersToDisplay = 5 })
        </li>

    </ul>
</div>