MVC3/Notesmarketplace1/Models/AddCategory.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Notesmarketplace1.Models
{
    public class AddCategory
    {
        [Required]
        public string name { get; set; }
        [Required]
        public string Description { get; set; }

    }
}

MVC3/Notesmarketplace1/Models/Managesystem.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Notesmarketplace1.Models
{
    public class Managesystem
    {
        
        
        public string SupportEmailid{ get; set; }
        public string Password { get; set; }
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Not a valid phone number")]
        public string PhoneNumber { get; set; }
        public string EmailAddress { get; set; }
        public string Facebook { get; set; }
        public string Twitter { get; set; }
        public string Linkedin { get; set; }

        public HttpPostedFileBase ProfilePicture { get; set; }
        public HttpPostedFileBase DisplayPicture { get; set; }
        
        public string FileName { get; set; }
        public string FilePath { get; set; }
       

    }
}

MVC3/Notesmarketplace1/Models/addcountry.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Notesmarketplace1.Models
{
    public class addcountry
    {
        [Required]
        public string name { get; set; }
        [Required]
        public string CountryCode { get; set; }
    }
}

MVC3/Notesmarketplace1/Controllers/ManageSystemController.cs
using Notesmarketplace1.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;

namespace Notesmarketplace1.Controllers
{
    public class ManageSystemController : Controller
    {
        private readonly notemarketplaceEntities dbobj = new notemarketplaceEntities();
        // GET: ManageSystem
        [Authorize(Roles = "SuperAdmin")]
        public ActionResult ManageSystemConfiguration()
        {
            return View();
        }
        [HttpPost]
        public ActionResult ManageSystemConfiguration(Managesystem managesystem)
        {
            var Emailid = User.Identity.Name.ToString();
            User user = dbobj.Users.Where(x => x.EmailId == Emailid).FirstOrDefault();
            if (ModelState.IsValid)
            {


                SystemConfiguration systemConfiguration1 = new SystemConfiguration()
                {
                    Key = "SupportEmail",
                    Value = managesystem.SupportEmailid,
                    CreatedBy = user.ID,
                    CreatedDate = DateTime.Now,
                    ModifiedDate = DateTime.Now,
                    isActive = true,
                };
                dbobj.SystemConfigurations.Add(systemConfiguration1);
                dbobj.SaveChanges();

                SystemConfiguration systemConfiguration = new SystemConfiguration()
                {
                    Key = "Password",
                    Value = managesystem.Password,
                    CreatedBy = user.ID,
                    CreatedDate = DateTime.Now,
                    ModifiedDate = DateTime.Now,
                    isActive = true,
                };
                dbobj.SystemConfigurations.Add(systemConfiguration);
                dbobj.SaveChanges();
                SystemConfiguration systemConfiguration2 = new SystemConfiguration()
                {
                    Key = "SupportPhoneNumber",
                    Value = managesystem.PhoneNumber,
                    CreatedBy = user.ID,
                    CreatedDate = DateTime.Now,
                    ModifiedDate = DateTime.Now,
                    isActive = true,
                };
                dbobj.SystemConfigurations.Add(systemConfiguration2);
                dbobj.SaveChanges();
                SystemConfiguration systemConfiguration3 = new SystemConfiguration()
                {
                    Key = "EmailAddress",
                    Value = managesystem.EmailAddress,
                    CreatedBy = user.ID,
                    CreatedDate = DateTime.Now,
                    ModifiedDate = DateTime.Now,
                    isActive = true,
                };
                dbobj.SystemConfigurations.Add(systemConfiguration3);
                dbobj.SaveChanges();
                SystemConfiguration systemConfiguration4 = new SystemConfiguration()
                {
                    Key = "Facebook URL",
                    Value = managesystem.Facebook,
                    CreatedBy = user.ID,
                    CreatedDate = DateTime.Now,
                    ModifiedDate = DateTime.Now,
                    isActive = true,
                };
                dbobj.SystemConfigurations.Add(systemConfiguration4);
                dbobj.SaveChanges();
                SystemConfiguration systemConfiguration5 = new SystemConfiguration()
                {
                    Key = "Twitter URL",
                    Value = managesystem.Twitter,
                    CreatedBy = user.ID,
                    CreatedDate = DateTime.Now,
                    ModifiedDate = DateTime.Now,
                    isActive = true,
                };
                dbobj.SystemConfigurations.Add(systemConfiguration5);
                dbobj.SaveChanges();
                SystemConfiguration systemConfiguration6 = new SystemConfiguration()
                {
                    Key = "Linkedin URL",
                    Value = managesystem.Linkedin,
                    CreatedBy = user.ID,
                    CreatedDate = DateTime.Now,
                    ModifiedDate = DateTime.Now,
                    isActive = true,
                };
                dbobj.SystemConfigurations.Add(systemConfiguration6);
                dbobj.SaveChanges();
                SystemConfiguration systemConfiguration7 = new SystemConfiguration()
                {
                    Key = "DefaultImageforNote",
                    CreatedBy = user.ID,
                    CreatedDate = DateTime.Now,
                    ModifiedDate = DateTime.Now,
                    isActive = true,
                };
                string storepath = Server.MapPath("/System Configuration/DefaultImage/");
                if (managesystem.DisplayPicture != null && managesystem.DisplayPicture.ContentLength > 0)
                {
                    string _FileName = Path.GetFileNameWithoutExtension(managesystem.DisplayPicture.FileName);
                    string extension = Path.GetExtension(managesystem.DisplayPicture.FileName);
                    _FileName = "DN" + extension;
                    string finalpath = Path.Combine(storepath, _FileName);
                    managesystem.DisplayPicture.SaveAs(finalpath);
                    systemConfiguration7.Value = Path.Combine(("/System Configuration/DefaultImage/"), _FileName);
                    dbobj.SystemConfigurations.Add(systemConfiguration7);
                    dbobj.SaveChanges();
                }
                SystemConfiguration systemConfiguration8 = new SystemConfiguration()
                {
                    Key = "DefaultProfilePicture",
                    CreatedBy = user.ID,
                    CreatedDate = DateTime.Now,
                    ModifiedDate = DateTime.Now,
                    isActive = true,
                };
                string storepath1 = Server.MapPath("/System Configuration/DefaultImage/");
                if (managesystem.ProfilePicture != null && managesystem.ProfilePicture.ContentLength > 0)
                {
                    string _FileName1 = Path.GetFileNameWithoutExtension(managesystem.ProfilePicture.FileName);
                    string extension1 = Path.GetExtension(managesystem.ProfilePicture.FileName);
                    _FileName1 = "DP" + extension1;
                    string finalpath1 = Path.Combine(storepath1, _FileName1);
                    managesystem.ProfilePicture.SaveAs(finalpath1);
                    systemConfiguration8.Value = Path.Combine(("/System Configuration/DefaultImage/"), _FileName1);
                    dbobj.SystemConfigurations.Add(systemConfiguration8);
                    dbobj.SaveChanges();
                }
            }

            return RedirectToAction("AdminDashboard", "Admin");
        }
        [Authorize(Roles = "SuperAdmin")]
        public ActionResult ManageAdministrator(string search, int? page, string sortorder, string currentFilter)
        {
            ViewBag.CurrentSort = sortorder;
            ViewBag.AddedDateparam = string.IsNullOrEmpty(sortorder) ? "Date Desc" : "";
            ViewBag.Firstnameparam = sortorder == "fname" ? "fname_desc" : "fname";
            ViewBag.Lastnameparam = sortorder == "lname" ? "lname_desc" : "lname";
            ViewBag.Emailparam = sortorder == "Type" ? "Type_desc" : "Type";
            ViewBag.Typeparam = sortorder == "type1" ? "type1_desc" : "type1";
            var users = dbobj.Users.Where(x => x.UserRole.Name == "Admin" && ((x.FirstName.Contains(search) || x.LastName.Contains(search) || x.EmailId.Contains(search)
            || x.CreatedDate.ToString().Contains(search) || x.UserProfiles.Where(a => a.UserId == a.User.ID).Select(a => a.PhoneNumber).Contains(search) || search == null)));
            if (search != null)
            {
                page = 1;
            }
            else
            {
                search = currentFilter;
            }

            switch (sortorder)
            {
                case "Date Desc":
                    users = users.OrderByDescending(x => x.CreatedDate);
                    break;
                case "fname":
                    users = users.OrderByDescending(x => x.FirstName);
                    break;
                case "fname_desc":
                    users = users.OrderBy(x => x.FirstName);
                    break;
                case "lname":
                    users = users.OrderByDescending(x => x.LastName);
                    break;
                case "lname_desc":
                    users = users.OrderBy(x => x.LastName);
                    break;
                case "type1":
                    users = users.OrderByDescending(x => x.IsActive);
                    break;
                case "type1_desc":
                    users = users.OrderBy(x => x.IsActive);
                    break;
                default:
                    users = users.OrderBy(x => x.CreatedDate);
                    break;
            }

            return View(users.ToList().ToPagedList(page ?? 1, 5));
        }
        public ActionResult AddAdministrator(int? id)
        {
            var Emailid = User.Identity.Name.ToString();
            User user1 = dbobj.Users.Where(x => x.EmailId == Emailid).FirstOrDefault();
            User user = dbobj.Users.Find(id);
            UserProfile userProfile = dbobj.UserProfiles.Where(x => x.UserId == user.ID).FirstOrDefault();
            if (user != null)
            {
                ViewBag.countrycode = dbobj.Countries.Where(x => x.isActive == true);
                UpdateProfile update = new UpdateProfile
                {
                    FirstName = user.FirstName,
                    LastName = user.LastName,
                    EmailId = user.EmailId,
                    PhoneNumber = userProfile.PhoneNumber,

MVC3/Notesmarketplace1/Views/ManageSystem/AddAdministrator.cshtml
@model Notesmarketplace1.Models.UpdateProfile
@{
    ViewBag.Title = "AddAdministrator";
}
@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<section id="myprofile">
    <div class="container-mp">
        <h1>Add Administrator</h1>
        @using (Html.BeginForm("AddAdministrator", "ManageSystem", FormMethod.Post))
        {

            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="exampleInputPassword1" class="mp01"><span>First Name<span class="required">*</span></span></label>
                        @Html.TextBoxFor(model => model.FirstName, new { @class = "form-control mp02", @PlaceHolder = "Enter Your FirstName" })

                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="exampleInputPassword1" class="mp01"><span>Last Name<span class="required">*</span></span></label>
                        @Html.TextBoxFor(model => model.LastName, new { @class = "form-control mp02", @PlaceHolder = "Enter Your LastName" })

                    </div>

                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="exampleInputPassword1" class="mp01">Email<span class="required">*</span></label>
                        @Html.TextBoxFor(x => x.EmailId, new { @class = "form-control mp02 ", @PlaceHolder = "Enter Your email address" })


                    </div>
                </div>
            </div>

            <label for="exampleInputPassword1" class="mp01">Phone Number</label>
            <div class="row">

                <div class="col-md-2">
                    <div class="form-group">
                        @Html.DropDownList("Phonenumbercountrycode", new SelectList(ViewBag.countrycode, "ID", "CountryCode"), "", new { @class = "form-control mp05" })

                    </div>
                </div>
                <div class="col-md-4">
                    @Html.TextBoxFor(x => x.PhoneNumber, new { @class = "form-control mp04 ", @PlaceHolder = "Enter Your phone number", @id = "Phone" })

                    @Html.ValidationMessageFor(x => x.PhoneNumber, "", new { @class = "text-danger" })

                </div>



            </div>
            <button class="btn btn-primary" type="submit" id="btn-submit">SUBMIT</button>
        }
    </div>
</section>

MVC3/Notesmarketplace1/Views/ManageSystem/AddCategory.cshtml
@model Notesmarketplace1.Models.AddCategory
@{
    ViewBag.Title = "AddCategory";
}
@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<section id="myprofile">
    <div class="container-mp">
        <h1>Add Category</h1>
        @using (Html.BeginForm("AddCategory", "ManageSystem", FormMethod.Post))
        {
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="exampleInputPassword1" class="mp01"><span>Category Name<span class="required">*</span></span></label>
                        @Html.TextBoxFor(model => model.name, new { @class = "form-control mp02", @PlaceHolder = "Enter category name" })
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="exampleInputPassword1" class="mp01">Description<span class="required">*</span></label>
                        @Html.TextBoxFor(model => model.Description,new { @class = "form-control ac", @PlaceHolder = "Enter your description"} )
                    </div>
                </div>
            </div>
            <button class="btn btn-primary" type="submit" id="btn-submit">SUBMIT</button>
        }
        </div>
</section>

MVC3/Notesmarketplace1/Views/ManageSystem/AddCountry.cshtml
@model Notesmarketplace1.Models.addcountry

@{
    ViewBag.Title = "AddCountry";
}

@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<section id="myprofile">
    <div class="container-mp">
        <h1>Add Category</h1>
        @using (Html.BeginForm("AddCountry", "ManageSystem", FormMethod.Post))
        {
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="exampleInputPassword1" class="mp01"><span>Country Name<span class="required">*</span></span></label>
                        @Html.TextBoxFor(model => model.name, new { @class = "form-control mp02", @PlaceHolder = "Enter Country  name" })
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="exampleInputPassword1" class="mp01"><span>Country Code<span class="required">*</span></span></label>
                        @Html.TextBoxFor(model => model.CountryCode, new { @class = "form-control mp02", @PlaceHolder = "Enter Country code" })
                    </div>
                </div>
            </div>
            <button class="btn btn-primary" type="submit" id="btn-submit">SUBMIT</button>
        }
        </div>
</section>

MVC3/Notesmarketplace1/Views/ManageSystem/AddType.cshtml
@model Notesmarketplace1.Models.AddCategory
@{
    ViewBag.Title = "AddType";
}
@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<section id="myprofile">
    <div class="container-mp">
        <h1>Add Type</h1>
        @using (Html.BeginForm("AddType", "ManageSystem", FormMethod.Post))
        {
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="exampleInputPassword1" class="mp01"><span>Type<span class="required">*</span></span></label>
                        @Html.TextBoxFor(model => model.name, new { @class = "form-control mp02", @PlaceHolder = "Enter type name" })
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="exampleInputPassword1" class="mp01">Description<span class="required">*</span></label>
                        @Html.TextBoxFor(model => model.Description, new { @class = "form-control ac", @PlaceHolder = "Enter your description" })

                    </div>
                </div>
            </div>
            <button class="btn btn-primary" type="submit" id="btn-submit">SUBMIT</button>
        }
        </div>
</section>

MVC3/Notesmarketplace1/Views/ManageSystem/ManageAdministrator.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<Notesmarketplace1.Models.User>

@{
    ViewBag.Title = "ManageAdministrator";
}
@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<section id="myprofile">
    <div class="container-mp">
        <h1>Manage Administrator</h1>
        <div class="progressn">
            <div class="section">
                <div class="row">
                    <div class="col-md-6">
                        <a href="/ManageSystem/AddAdministrator"><button id="button-add-admin">ADD ADMINISTRATOR</button></a>
                    </div>
                    @using (Html.BeginForm("ManageAdministrator", "ManageSystem", FormMethod.Get))
                    {
                        <div class="col-md-6 ">
                            <div class="btn-search">
                                <input type="text" name="search" id="place-search" placeholder="   &#xF002;    Search">
                                <button type="submit" id="button-search">SEARCH</button>
                            </div>
                        </div>
                    }
                </div>
            </div>
            <div class="table-responsive">
                <table class="table border">
                    <thead>
                        <tr style="height: 75px; font-weight: 600;">
                            <th scope="col" style="vertical-align: middle;text-align:center;">SR NO.</th>
                            <th scope="col" style="vertical-align: middle;text-align:center;">
                                @Html.ActionLink("FIRST NAME", "ManageAdministrator", new { sortorder = ViewBag.Firstnameparam })
                            </th>
                            <th scope="col" style="vertical-align: middle;text-align:center;">
                                @Html.ActionLink("LAST NAME", "ManageAdministrator", new { sortorder = ViewBag.Lastnameparam })
                            </th>
                            <th scope="col" style="vertical-align: middle;text-align:center;">
                                @Html.ActionLink("EMAIL", "ManageAdministrator", new { sortorder = ViewBag.Emailparam })
                            </th>
                            <th scope="col" style="vertical-align: middle;text-align:center;">
                                @Html.ActionLink("PHONE NO.", "ManageAdministrator", new { sortorder = ViewBag.phoneparam })

                            <th scope="col" style="vertical-align: middle;text-align:center;">
                                @Html.ActionLink("DATA ADDED", "ManageAdministrator", new { sortorder = ViewBag.AddedDateparam })

                            <th scope="col" style="vertical-align: middle;text-align:center;">
                                @Html.ActionLink("ACTIVE", "ManageAdministrator", new { sortorder = ViewBag.Typeparam })

                            <th scope="col" style="vertical-align: middle;text-align:center;">ACTION</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (Model.Count() == 0)
                        {
                            <tr>
                                <td colspan="6" class="text-center">
                                    No any record found
                                </td>
                            </tr>
                        }
                        @{
                            var count = 0;
                        }

                        @foreach (var item in Model)
                        {
                            <tr class="table1">

                                <td style="vertical-align: middle;text-align:center;"> @(count + ((Model.PageNumber - 1) * Model.PageSize) + 1)</td>
                                <td style="vertical-align: middle;text-align:center;">@item.FirstName</td>
                                <td style="vertical-align: middle;text-align:center;">@item.LastName</td>
                                <td style="vertical-align: middle;text-align:center;">@item.EmailId</td>
                                <td style="vertical-align: middle;text-align:center;">@item.UserProfiles.Where(x => x.UserId == x.User.ID).Select(x => x.PhoneNumber).FirstOrDefault()</td>

                                <td style="vertical-align: middle;text-align:center;">@item.CreatedDate</td>
                                <td style="vertical-align: middle;text-align:center;">
                                    @if (@item.IsActive)
                                    {
                                        <p>Yes</p>
                                    }
                                    else
                                    {
                                        <p>No</p>
                                    }
                                </td>
                                <td style="vertical-align: middle;text-align:center;"><a href="/ManageSystem/AddAdministrator/@item.ID"><img src="~/Content/img/Dashboard/edit.png"></a><a href="/ManageSystem/DeleteAdmin/@item.ID"><img src="~/Content/img/front-images/delete.png" onclick="return confirm('Are you sure you wants to make this administrator inactive?');"></a></td>

                            </tr>
                            count++;
                        }

                    </tbody>
                </table>
            </div>
        </div>
        <div class="text-center">
            <ul class="pagination">
                <li>
                    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

                    @Html.PagedListPager(Model, page => Url.Action("ManageAdministrator",
                        new { page, sortorder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter })
               , new PagedListRenderOptions() { MaximumPageNumbersToDisplay = 5 })
                </li>
            </ul>
        </div>
    </div>

MVC3/Notesmarketplace1/Views/ManageSystem/ManageCategory.cshtml
@using PagedList;
@using PagedList.Mvc;

@model IPagedList<Notesmarketplace1.Models.NoteCategory>
@{
    ViewBag.Title = "ManageCategory";
}
@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<section id="myprofile">
    <div class="container-mp">
        <h1>Manage Category</h1>
        <div class="progressn">
            <div class="section">
                <div class="row">
                    <div class="col-md-6">
                        <a href="/ManageSystem/AddCategory"> <button id="button-add-category">ADD CATEGORY</button></a>
                    </div>
                    @using (Html.BeginForm("ManageCategory", "ManageSystem", FormMethod.Get))
                    {
                        <div class="col-md-6 ">
                            <div class="btn-search">
                                <input type="text" name="search" id="place-search" placeholder="   &#xF002;    Search">
                                <button type="submit" id="button-search">SEARCH</button>
                            </div>
                        </div>
                    }
                </div>

            </div>
            <div class="table-responsive">
                <table class="table border common-table-width">
                    <thead>
                        <tr style="height: 75px; font-weight: 600;">
                            <th scope="col" style="vertical-align: middle;text-align:center;">SR NO.</th>
                            <th scope="col" style="vertical-align: middle;text-align:center;">
                                @Html.ActionLink("CATEGORY", "ManageCategory", new { sortorder = ViewBag.nameparam })
                            </th>
                            <th scope="col" style="vertical-align: middle;text-align:center;">
                                @Html.ActionLink("DESCRIPTION", "ManageCategory", new { sortorder = ViewBag.Descriptionparam })
                            </th>

                            <th scope="col" style="vertical-align: middle;text-align:center;">
                                @Html.ActionLink("DATE ADDED", "ManageCategory", new { sortorder = ViewBag.AddedDateparam })
                            </th>
                            <th scope="col" style="vertical-align: middle;text-align:center;">
                                @Html.ActionLink("ADDEDBY", "ManageCategory", new { sortorder = ViewBag.Addedparam })
                            </th>
                            

                            <th scope="col" style="vertical-align: middle;text-align:center;">
                                @Html.ActionLink("ACTIVE", "ManageCategory", new { sortorder = ViewBag.Typeparam })
                            </th>

                            <th scope="col" style="vertical-align: middle;text-align:center;">ACTION</th>


                        </tr>
                    </thead>
                    <tbody>
                        @if (Model.Count() == 0)
                        {
                            <tr>
                                <td colspan="6" class="text-center">
                                    No any record found
                                </td>
                            </tr>
                        }
                        @{
                            var count = 0;
                        }

                        @foreach (var item in Model)
                        {
                            <tr class="table1">

                                <td style="vertical-align: middle;text-align:center;">@(count + ((Model.PageNumber - 1) * Model.PageSize) + 1)</td>
                                <td style="vertical-align: middle;text-align:center;">@item.name</td>
                                <td style="vertical-align: middle;text-align:center;">@item.Description</td>

                                <td style="vertical-align: middle;text-align:center;">@item.Createddate</td>
                                <td style="vertical-align: middle;text-align:center;">
                                    @item.User.NoteCategories.Where(x => x.CreatedBy == x.User.ID).Select(x => x.User.FirstName).FirstOrDefault()
                                    @item.User.NoteCategories.Where(x => x.CreatedBy == x.User.ID).Select(x => x.User.LastName).FirstOrDefault()
                                </td>
                                <td style="vertical-align: middle;text-align:center;">
                                    @if (@item.isActive)
                                    {
                                        <p>Yes</p>
                                    }
                                    else
                                    {
                                        <p>No</p>
                                    }
                                </td>
                                <td style="vertical-align: middle;text-align:center;"><a href="/ManageSystem/AddCategory/@item.Id"><img src="~/Content/img/Dashboard/edit.png"></a><a href="/ManageSystem/DeleteCategory/@item.Id"><img src="~/Content/img/front-images/delete.png" onclick="return confirm('Are you sure you wants to make this Category inactive?');"></a></td>


                            </tr>
                            count++;
                        }

                    </tbody>
                </table>
            </div>
        </div>
        <div class="text-center">
            <ul class="pagination">
                <li>
                    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

                    @Html.PagedListPager(Model, page => Url.Action("ManageCategory",
                        new { page, sortorder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter })
               , new PagedListRenderOptions() { MaximumPageNumbersToDisplay = 5 })
                </li>
            </ul>
        </div>
    </div>

</section>