MVC3/Notesmarketplace1/Controllers/UserActivityController.cs
using Ionic.Zip;
using Notesmarketplace1.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;

namespace Notesmarketplace1.Controllers
{
    public class UserActivityController : Controller
    {
        // GET: UserActivity
        private readonly notemarketplaceEntities dbobj = new notemarketplaceEntities();
        [Authorize(Roles = "Member")]
        public ActionResult MyDownload(string search, string sort, int? page, string currentFilter)
        {
            var Emailid = User.Identity.Name.ToString();
            User user1 = dbobj.Users.Where(x => x.EmailId == Emailid).FirstOrDefault();

            List<Download> downloads = dbobj.Downloads.Where(x => x.downloader == user1.ID && x.isSellerhasAllowedDownloaded == true).ToList();
            List<UserProfile> userProfiles = dbobj.UserProfiles.ToList();
            List<User> user = dbobj.Users.ToList();

            var buyerrequest = (from dn in downloads
                                join u in user on dn.downloader equals u.ID into table1
                                from u in table1.ToList()
                                join up in userProfiles on dn.downloader equals up.UserId into table2
                                from up in table2.ToList().DefaultIfEmpty()

                                select new DownloadModel
                                { Downloaddetail = dn, Userprofiledetail = up, Userdetail = u }).AsQueryable();
            if (!String.IsNullOrEmpty(search))
            {
                buyerrequest = buyerrequest.Where(x => x.Userdetail.EmailId.Contains(search) ||
                x.Downloaddetail.NoteTitle.Contains(search) || x.Downloaddetail.NoteCategory.Contains(search) ||
                 x.Userprofiledetail.PhoneNumber.Contains(search) || x.Downloaddetail.PurchasedPrice.ToString().Contains(search) || search == null);

            }
            ViewBag.CurrentSort = sort;
            ViewBag.AddedDateparamPublished = string.IsNullOrEmpty(sort) ? "Date Desc1" : "";
            ViewBag.TitleparamPublished = sort == "Title1" ? "Title_desc1" : "Title1";
            ViewBag.CategoryparamPublished = sort == "Category1" ? "Category_desc1" : "Category1";
            ViewBag.SelltypeparamPublished = sort == "Type" ? "Type_desc" : "Type";
            ViewBag.PricepeparamPublished = sort == "Price" ? "Price_desc" : "Price";


            if (search != null)
            {
                page = 1;
            }
            else
            {
                search = currentFilter;
            }

            ViewBag.CurrentFilter = search;
            switch (sort)
            {

                case "Date Desc1":
                    buyerrequest = buyerrequest.OrderByDescending(x => x.Downloaddetail.AttachmentDownloadedDate);
                    break;
                case "Title1":
                    buyerrequest = buyerrequest.OrderByDescending(x => x.Downloaddetail.NoteTitle);
                    break;
                case "Title_desc1":
                    buyerrequest = buyerrequest.OrderBy(x => x.Downloaddetail.NoteTitle);
                    break;
                case "Category1":
                    buyerrequest = buyerrequest.OrderByDescending(x => x.Downloaddetail.NoteCategory);
                    break;
                case "Category_desc1":
                    buyerrequest = buyerrequest.OrderBy(x => x.Downloaddetail.NoteCategory);
                    break;
                case "Type":
                    buyerrequest = buyerrequest.OrderByDescending(x => x.Downloaddetail.Ispaid);
                    break;
                case "Type_desc":
                    buyerrequest = buyerrequest.OrderBy(x => x.Downloaddetail.Ispaid);
                    break;
                case "Price":
                    buyerrequest = buyerrequest.OrderByDescending(x => x.Downloaddetail.PurchasedPrice);
                    break;
                case "Price_desc":
                    buyerrequest = buyerrequest.OrderBy(x => x.Downloaddetail.PurchasedPrice);
                    break;
                default:
                    buyerrequest = buyerrequest.OrderByDescending(x => x.Downloaddetail.AttachmentDownloadedDate);
                    break;

            }
            return View(buyerrequest.ToPagedList(page ?? 1, 5));

        }
        public ActionResult Download(int Id)
        {
            SellerNote sellrnote = dbobj.SellerNotes.Find(Id);

            using (ZipFile zip = new ZipFile())
            {

                zip.AddDirectory(Server.MapPath("~/UploadFiles/" + sellrnote.SellerID + "/" + Id + "/" + "Attachments"));
                MemoryStream output = new MemoryStream();
                zip.Save(output);
                return File(output.ToArray(), "Attachments/zip", "Note.zip");
            }
        }
        public ActionResult Review()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Review(int id, string comments, int rate)
        {
            Download objdownload = dbobj.Downloads.Where(x => x.NoteId == id).FirstOrDefault();
            var Emailid = User.Identity.Name.ToString();
            User user = dbobj.Users.Where(x => x.EmailId == Emailid).FirstOrDefault();
            SellerNote sellrnote = dbobj.SellerNotes.Where(x => x.Id == id).FirstOrDefault();
            SellerNotesReview objseller = dbobj.SellerNotesReviews.Where(x => x.NoteId == sellrnote.Id && x.ReviewedByid == user.ID).FirstOrDefault();
            if (objseller != null)
            {
                objseller.Ratings = rate;
                objseller.Comments = comments;
                objseller.ModifiedBy = user.ID;
                objseller.Modifieddate = DateTime.Now;
                dbobj.Entry(objseller).State = EntityState.Modified;
                dbobj.SaveChanges();
            }
            else
            {
                SellerNotesReview objseller1 = new SellerNotesReview
                {
                    NoteId = sellrnote.Id,
                    Ratings = rate,
                    Comments = comments,
                    ReviewedByid = user.ID,
                    AgainstDownloadsId = objdownload.Id,
                    CreatedBy = objdownload.downloader,
                    CreatedDate = DateTime.Now,
                    IsActive = true
                };
                dbobj.SellerNotesReviews.Add(objseller1);
                dbobj.SaveChanges();
            }

            return RedirectToAction("Dashboard", "Notes");
        }
        [HttpPost]
        public ActionResult ReportanIssue(int id, string remarks)
        {
            var Emailid = User.Identity.Name.ToString();
            User user = dbobj.Users.Where(x => x.EmailId == Emailid).FirstOrDefault();
            SellerNote sellrnote = dbobj.SellerNotes.Where(x => x.Id == id).FirstOrDefault();
            Download objdownload = dbobj.Downloads.Where(x => x.NoteId == id).FirstOrDefault();
            SellerNotesReportedIssue reportedIssue = dbobj.SellerNotesReportedIssues.Where(x => x.NoteId == sellrnote.Id && x.ReportedByid == user.ID).FirstOrDefault();
            if (reportedIssue != null)
            {
                reportedIssue.Remarks = remarks;
                reportedIssue.Modifieddate = DateTime.Now;
                reportedIssue.ModifiedBy = user.ID;
                dbobj.Entry(reportedIssue).State = EntityState.Modified;
                dbobj.SaveChanges();
            }
            else
            {
                SellerNotesReportedIssue objseller1 = new SellerNotesReportedIssue
                {
                    NoteId = sellrnote.Id,
                    Remarks = remarks,
                    ReportedByid = user.ID,
                    againstDownloadId = objdownload.Id,
                    CreatedBy = objdownload.downloader,
                    CreatedDate = DateTime.Now,
                    IsActive = true
                };
                dbobj.SellerNotesReportedIssues.Add(objseller1);
                dbobj.SaveChanges();

            }
            SystemConfiguration system = dbobj.SystemConfigurations.Where(x => x.Key == "SupportEmail").FirstOrDefault();
            SystemConfiguration system1 = dbobj.SystemConfigurations.Where(x => x.Key == "Password").FirstOrDefault();
            SystemConfiguration system2 = dbobj.SystemConfigurations.Where(x => x.Key == "EmailAddress").FirstOrDefault();
            SendEmailtoAdmin(system.Value, system1.Value, system2.Value, id);
            return RedirectToAction("Dashboard", "Notes");

        }
        [NonAction]
        public void SendEmailtoAdmin(string support, string password, string emailID, int id)
        {

            SellerNote seller = dbobj.SellerNotes.Where(x => x.Id == id).FirstOrDefault();
            var Emailid = User.Identity.Name.ToString();
            User user = dbobj.Users.Where(x => x.EmailId == Emailid).FirstOrDefault();
            User user1 = dbobj.Users.Where(x => x.ID == seller.SellerID).FirstOrDefault();
            var fromEmail = new MailAddress(support, "Notemarketplace");
            var toEmail = new MailAddress(emailID);
            var fromEmailPassword = password; // Replace with actual password
            string subject = user.FirstName + " " + "Reported an issue for" + " " + seller.Title;
            string body = "Hello  Admin," + "<br/>";
            body += "<br/>We want to inform you that" + " " + user.FirstName + "  Reported an issue for" + " " + user1.FirstName + "'s   Note with";
            body += "<br/>title" + " " + seller.Title + "." + "Please look at the notes and take required actions.";
            body += "<br/><br/>Regards,<br/>";
            body += "Notes marketplace";
            var smtp = new SmtpClient
            {
                Host = "smtp.gmail.com",
                Port = 587,

MVC3/Notesmarketplace1/Views/UserActivity/MyDownload.cshtml
@using PagedList;
@using PagedList.Mvc;

@model IPagedList<Notesmarketplace1.Models.DownloadModel>

@{
    ViewBag.Title = "MyDownload";
}
@{
    Layout = "~/Views/Shared/_Layoutcommon.cshtml";

}

<div class="dashboard-title-wrapper">
    <div class="container-ds">
        <div class="mydownloads">
            <div class="title-section">
                <div class="row">

                    <div class="col-md-6">
                        <h2>My Downloads </h2>
                    </div>
                    @using (Html.BeginForm("MyDownload", "UserActivity", FormMethod.Get))
                    {
                        <div class="col-md-6 ">
                            <div class="btn-search">
                                <input type="text" name="search" id="place-search" placeholder="   &#xF002;    Search">
                                <button type="submit" id="button-search">SEARCH</button>
                            </div>
                        </div>
                    }
                </div>
            </div>
            <div class="table-responsive">
                <table class="table border">
                    <thead>
                        <tr style="height: 70px; font-weight: 600;">
                            <th scope="col" style="vertical-align: middle;text-align:center;">SR.NO.</th>
                            <th scope="col" style="vertical-align: middle;text-align:center;">
                                @Html.ActionLink(" NOTE TITLE", "MyDownload", new { sort = ViewBag.TitleparamPublished })
                            </th>
                            <th scope="col" style="vertical-align: middle;text-align:center;">
                                @Html.ActionLink("CATEGORY", "MyDownload", new { sort = ViewBag.CategoryparamPublished })
                            </th>
                            <th scope="col" style="vertical-align: middle;text-align:center;">BUYER</th>
                            <th scope="col" style="vertical-align: middle;text-align:center;">
                                @Html.ActionLink("SELL TYPE", "MyDownload", new { sort = ViewBag.SelltypeparamPublished })
                            </th>
                            <th scope="col" style="vertical-align: middle;text-align:center;">
                                @Html.ActionLink("PRICE", "MyDownload", new { sort = ViewBag.PricepeparamPublished })
                            </th>
                            <th scope="col" style="vertical-align: middle;text-align:center;">
                                @Html.ActionLink("DOWNLOAD DATE/TIME", "MyDownload", new { sort = ViewBag.AddedDateparamPublished })
                            </th>
                            <th scope="col"> </th>
                            <th scope="col"> </th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (Model.Count() == 0)
                        {
                            <tr>
                                <td colspan="6" class="text-center">
                                    No any record found
                                </td>
                            </tr>
                        }
                        @{
                            var count = 0;
                        }
                        @foreach (var item in Model)
                        {
                            <tr class="table2">
                                <td>
                                    @(count + ((Model.PageNumber - 1) * Model.PageSize) + 1)
                                </td>
                                    <td ><a href="/Notes/NotesDetail/@item.Downloaddetail.NoteId" style="color: #6255a5;">@item.Downloaddetail.NoteTitle</a></td>
                                    <td>@item.Downloaddetail.NoteCategory</td>
                                    <td>@item.Userdetail.EmailId</td>
                                    <td>
                                        @if (@item.Downloaddetail.Ispaid == true)
                                        {
                                            <p>Paid</p>
                                        }
                                        else
                                        {
                                            <p>Free</p>
                                        }
                                    </td>
                                    <td>$@item.Downloaddetail.PurchasedPrice</td>
                                    <td>@item.Downloaddetail.AttachmentDownloadedDate</td>
                                    <td>
                                        <a href="/Notes/NotesDetail/@item.Downloaddetail.NoteId"><img src="~/Content/img/Dashboard/eye.png" role="button" /></a>
                                    </td>
                                    <td>
                                        <div class="dropdown">
                                            <img src="~/Content/img/front-images/dots.png" class="dots" />
                                            <div class="dropdown-content">
                                                <a href="/UserActivity/Download/@item.Downloaddetail.NoteId">Download Note</a>
                                                <a href="/UserActivity/Review/@item.Downloaddetail.NoteId" data-toggle="modal" data-target="#exampleModal">Add Reviews/Feedback</a>
                                                <a  data-toggle="modal" data-target="#exampleModal_@item.Downloaddetail.NoteId">Report as inappropriate</a>
                                            </div>
                                        </div>
                                        <!-- add review -->
                                        <div class="modal fade " id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalScrollableTitle" aria-hidden="true">
                                            <div class="modal-dialog" role="document">
                                                <div class="modal-content">

                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                                    <div class="modal-body">
                                                        @using (Html.BeginForm("Review", "UserActivity", FormMethod.Post))
                                                        {
                                                            <h4 class="star-head">Add Review</h4>
                                                            <div class="rate img-responsive">
                                                                <input type="radio" id="star5" name="rate" value="5" />
                                                                <label for="star5" title="text">★ </label>
                                                                <input type="radio" id="star4" name="rate" value="4" />
                                                                <label for="star4" title="text">★ </label>
                                                                <input type="radio" id="star3" name="rate" value="3" />
                                                                <label for="star3" title="text">★ </label>
                                                                <input type="radio" id="star2" name="rate" value="2" />
                                                                <label for="star2" title="text">★ </label>
                                                                <input type="radio" id="star1" name="rate" value="1" />
                                                                <label for="star1" title="text">★ </label>
                                                            </div>
                                                            <br> <br><br>
                                                            <input type="hidden" name="id" value="@item.Downloaddetail.NoteId" />
                                                            <label for="text-area"><span class="review-label required">Comments/quetions*</span></label>
                                                            <textarea class="form-control required user" placeholder="comments..." rows="5" name="comments"></textarea>
                                                            <button type="submit" class="btn-userP btn-review">SUBMIT</button>

                                                        }
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <!-- Report an issue popup -->
                                        <div class="modal fade" id="exampleModal_@item.Downloaddetail.NoteId" tabindex="-1" role="dialog" aria-labelledby="exampleModalScrollableTitle" aria-hidden="true">
                                            <div class="modal-dialog" role="document">
                                                <div class="modal-content Rejectpopup">
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close" value="Cancel">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                                    @using (Html.BeginForm("ReportanIssue", "UserActivity", FormMethod.Post))
                                                    {
                                                        <div class="modal-body">
                                                            <input type="hidden" name="id" value="@item.Downloaddetail.NoteId" />
                                                            <h4 class="star-head">@item.Downloaddetail.NoteTitle</h4>

                                                            <label for="text-area"><span class="review-label">Remarks*</span></label>
                                                            <textarea class="form-control user" placeholder="Write Remarks" rows="7" name="remarks" required></textarea>
                                                            <br>
                                                            <form style="float:right; margin-bottom:20px;">
                                                                <button type="submit" class="btn btn-primary button-report" onclick="return confirm('Are you sure you want to mark this report as spam,you cannot update later ?');">Report an Issue</button><button type="button" class="btn btn-primary cancel-button button-blue" data-dismiss="modal" aria-label="Close" value="Cancel">Cancel</button>

                                                            </form>
                                                        </div>
                                                    }
                                                </div>

                                            </div>
                                        </div>



                                    </td>
                                  </tr>
                            count++;
                        }

                    </tbody>
                </table>
            </div>
        </div>
        <div class="text-center">
            <ul class="pagination">
                <li>
                    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

                    @Html.PagedListPager(Model, page => Url.Action("MyDownload",
                        new { page, sort = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter })
               , new PagedListRenderOptions() { MaximumPageNumbersToDisplay = 5 })
                </li>
            </ul>
        </div>
    </div>
</div>

MVC3/Notesmarketplace1/Views/UserActivity/MyRejected.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<Notesmarketplace1.Models.DashboardClass>
@{
    ViewBag.Title = "MyRejected";
}
@{
    Layout = "~/Views/Shared/_Layoutcommon.cshtml";

}
<div class="dashboard-title-wrapper">
    <div class="container-ds">
        <div class="mydownloads">
            <div class="title-section">
                <div class="row">
                    <div class="col-md-6">
                        <h2>My Rejected Notes</h2>
                    </div>
                    @using (Html.BeginForm("MyRejected", "UserActivity", FormMethod.Get))
                    {
                        <div class="col-md-6 ">
                            <div class="btn-search">
                                <input type="text" id="place-search" name="searchtext" placeholder="   &#xF002;    Search">
                                <button type="submit" id="button-search">SEARCH</button>
                            </div>
                        </div>
                    }
                </div>
            </div>
            <div class="table-responsive">
                <table class="table border">
                    <thead>
                        <tr style="height: 70px; font-weight: 600;">
                            <th style="vertical-align: middle;text-align:center;" scope="col">SR NO.</th>
                            <th style="vertical-align: middle;text-align:center;" scope="col">
                                @Html.ActionLink("NOTE TITLE", "MyRejected", new { sortorder = ViewBag.Titleparam })
                            </th>
                            <th style="vertical-align: middle;text-align:center;" scope="col">
                                @Html.ActionLink("CATEGORY", "MyRejected", new { sortorder = ViewBag.Categoryparam })
                            </th>
                            <th style="vertical-align: middle;text-align:center;" scope="col">
                                @Html.ActionLink("REMARKS", "MyRejected", new { sortorder = ViewBag.Statuspeparam })
                            </th>
                            <th style="vertical-align: middle;text-align:center;" scope="col">
                                @Html.ActionLink("DATE EDITED", "MyRejected", new { sortorder = ViewBag.AddedDateparam })
                            </th>
                            <th style="vertical-align: middle;text-align:center;" scope="col"> CLONE</th>
                            <th scope="col"> </th>

                        </tr>
                    </thead>
                    <tbody>
                        @if (Model.Count() == 0)
                            {
                                <tr>
                                    <td colspan="6" class="text-center">
                                        No any record found
                                    </td>
                                </tr>
                            }
                        @{
                                var count = 0;
                            }
                        @foreach (var item in Model)
                        {
                    <tr class="table2">
                        <td style="vertical-align: middle;text-align:center;">@(count + ((Model.PageNumber - 1) * Model.PageSize) + 1)</td>
                        <td style="color: #6255a5; vertical-align: middle;text-align:center;">@item.sellernotedetail.Title</td>
                        <td style="vertical-align: middle;text-align:center;">@item.notecategorydetail.name</td>
                        <td style="vertical-align: middle;text-align:center;">@item.sellernotedetail.AdminRemarks</td>
                        <td style="vertical-align: middle;text-align:center;">@item.sellernotedetail.ModifiedDate</td>
                        <td style=" vertical-align: middle;text-align:center;"><a href="/UserActivity/Clone/@item.sellernotedetail.Id" style="color: #6255a5;">Clone</a></td>
                        <td style="vertical-align: middle;text-align:center;">
                            <div class="dropdown1">
                                <img src="~/Content/img/front-images/dots.png" class="dots">
                                <div class="dropdown-content1">
                                    <a href="/UserActivity/Download/@item.sellernotedetail.Id">Download Note</a>
                                </div>
                            </div>
                        </td>

                    </tr>
                            count++;
                        }
                       
                    </tbody>
                </table>
            </div>
        </div>
        <div class="text-center">
            <ul class="pagination">
                <li>
                    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

                    @Html.PagedListPager(Model, page => Url.Action("MyRejected",
                        new { page, sortorder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter })
               , new PagedListRenderOptions() { MaximumPageNumbersToDisplay = 5 })
                </li>
            </ul>
        </div>

    </div>
</div>